services:
  authe:
    image: "${AUTHE_IMAGE:-ghcr.io/radio-aktywne/authe}:${AUTHE_TAG:-latest}"
    ports:
      - "${AUTHE_PUBLISHED_PORT:-23000}:23000"
      - "${AUTHE_PUBLISHED_ADMIN_PORT:-23001}:23001"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "AUTHE_DB_ADDRESS=${AUTHE_DB_ADDRESS:-authe-db:22000}"
      - "AUTHE_DB_PASSWORD=${AUTHE_DB_PASSWORD:-password}"
      - "AUTHE_AUTHGATE_PUBLIC_URL=${AUTHE_AUTHGATE_PUBLIC_URL:-https://authgate.traefik.me}"
      - "AUTHE_COOKIE_DOMAIN=${AUTHE_COOKIE_DOMAIN:-traefik.me}"
      - "AUTHE_ALLOWED_RETURN_URLS=${AUTHE_ALLOWED_RETURN_URLS:-http://*.traefik.me,https://*.traefik.me}"
    volumes:
      - authe-certs:/etc/certs
