services:
  autho:
    image: "${AUTHO_IMAGE:-ghcr.io/radio-aktywne/autho}:${AUTHO_TAG:-latest}"
    ports:
      - "${AUTHO_PUBLISHED_PORT:-24000}:24000"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autho.rule=HostRegexp(`autho{suffix:.*}.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.autho.service=autho"
      - "traefik.http.services.autho.loadbalancer.server.port=24000"
      - "traefik.http.services.autho.loadbalancer.server.scheme=https"
      - "traefik.http.services.autho.loadbalancer.serverstransport=autho@file"
    environment:
      - "AUTHO_AUTHE_URL=${AUTHO_AUTHE_URL:-https://authe:23000}"
      - "AUTHO_AUTHGATE_PUBLIC_URL=${AUTHO_AUTHGATE_PUBLIC_URL:-https://authgate.traefik.me}"
    volumes:
      - autho-certs:/etc/certs
