services:
  authe:
    image: "${AUTHE_IMAGE:-ghcr.io/radio-aktywne/authe}:${AUTHE_TAG:-latest}"
    ports:
      - "${AUTHE_PUBLISHED_PORT:-23000}:23000"
      - "${AUTHE_PUBLISHED_ADMIN_PORT:-23001}:23001"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "AUTHE_DB_ADDRESS=${AUTHE_DB_ADDRESS:-authe-db:22000}"
      - "AUTHE_WEBAUTH_PUBLIC_URL=${AUTHE_WEBAUTH_PUBLIC_URL:-http://localhost:21000}"
      - "AUTHE_ALLOWED_RETURN_URLS=${AUTHE_ALLOWED_RETURN_URLS:-http://localhost:21000,http://localhost:20000,http://localhost:20001,http://localhost:13000,http://localhost:12000,http://localhost:12001,http://radioaktywne.pl,http://*.radioaktywne.pl}"
