services:
  autho:
    image: "${AUTHO_IMAGE:-ghcr.io/radio-aktywne/autho}:${AUTHO_TAG:-latest}"
    ports:
      - "${AUTHO_PUBLISHED_PORT:-24000}:24000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "AUTHO_AUTHE_URL=${AUTHO_AUTHE_URL:-https://authe:23000}"
      - "AUTHO_AUTHGATE_PUBLIC_URL=${AUTHO_AUTHGATE_PUBLIC_URL:-https://authgate.traefik.me}"
    volumes:
      - autho-certs:/etc/certs
