version: "3.9"

services:
  emission:
    extends:
      file: ./emission/docker-compose.yml
      service: emission

  fusion:
    extends:
      file: ./fusion/docker-compose.yml
      service: fusion

  decay:
    extends:
      file: ./decay/docker-compose.yml
      service: decay
