services:
  emiweb:
    extends:
      file: ./emiweb.yaml
      service: emiweb
    depends_on:
      - webauth
      - authgate
      - emigate

  authopsy:
    extends:
      file: ./authopsy.yaml
      service: authopsy
    depends_on:
      - authe
      - certifier

  webauth:
    extends:
      file: ./webauth.yaml
      service: webauth
    depends_on:
      - authgate
      - certifier

  emigate:
    extends:
      file: ./emigate.yaml
      service: emigate
    depends_on:
      - authgate
      - emishows
      - emistream
      - emipass
      - certifier

  authgate:
    extends:
      file: ./authgate.yaml
      service: authgate
    depends_on:
      - authe
      - autho
      - certifier

  autho:
    extends:
      file: ./autho.yaml
      service: autho
    depends_on:
      - authe
      - certifier

  authe:
    extends:
      file: ./authe.yaml
      service: authe
    depends_on:
      - authe-db
      - certifier

  authe-db:
    extends:
      file: ./authe-db.yaml
      service: authe-db
    depends_on:
      - certifier

  emipass:
    extends:
      file: ./emipass.yaml
      service: emipass
    depends_on:
      - emistream

  webscheduler:
    extends:
      file: ./webscheduler.yaml
      service: webscheduler
    depends_on:
      - emischeduler

  emischeduler:
    extends:
      file: ./emischeduler.yaml
      service: emischeduler
    depends_on:
      - emishows
      - emistream
      - emiarchive

  emishows:
    extends:
      file: ./emishows.yaml
      service: emishows
    depends_on:
      - emishows-db
      - emitimes

  emishows-db:
    extends:
      file: ./emishows-db.yaml
      service: emishows-db

  emitimes:
    extends:
      file: ./emitimes.yaml
      service: emitimes

  emistream:
    extends:
      file: ./emistream.yaml
      service: emistream
    depends_on:
      - emirecorder
      - fusion

  emirecorder:
    extends:
      file: ./emirecorder.yaml
      service: emirecorder
    depends_on:
      - emiarchive

  emiarchive:
    extends:
      file: ./emiarchive.yaml
      service: emiarchive

  fusion:
    extends:
      file: ./fusion.yaml
      service: fusion
    depends_on:
      - streamcast

  streamcast:
    extends:
      file: ./streamcast.yaml
      service: streamcast

  proxy:
    extends:
      file: ./proxy.yaml
      service: proxy
    depends_on:
      - certifier

  certifier:
    extends:
      file: ./certifier.yaml
      service: certifier

volumes:
  authopsy-certs:
  webauth-certs:
  emigate-backend-certs:
  authgate-frontend-certs:
  authgate-backend-certs:
  autho-certs:
  authe-certs:
  authe-db:
  authe-db-certs:
  emischeduler:
  emishows-certs:
  emishows-db:
  emishows-db-certs:
  emitimes:
  emiarchive:
  proxy-frontend-certs:
  proxy-backend-certs:
