version: "3.9"

services:
  emission:
    extends:
      file: ./emission/docker-compose.yml
      service: emission
    depends_on:
      - fusion

  fusion:
    extends:
      file: ./fusion/docker-compose.yml
      service: fusion
    depends_on:
      - decay

  decay:
    extends:
      file: ./decay/docker-compose.yml
      service: decay
