services:
  emiweb:
    extends:
      file: ./emiweb.yaml
      service: emiweb
    image: "${EMIWEB_IMAGE:-radio-aktywne/emiweb}"
    build: "${EMIWEB_PATH:-./emiweb}"
    depends_on:
      - webauth
      - authgate
      - emigate

  authopsy:
    extends:
      file: ./authopsy.yaml
      service: authopsy
    image: "${AUTHOPSY_IMAGE:-radio-aktywne/authopsy}"
    build: "${AUTHOPSY_PATH:-./authopsy}"
    depends_on:
      - authe
      - certifier

  webauth:
    extends:
      file: ./webauth.yaml
      service: webauth
    image: "${WEBAUTH_IMAGE:-radio-aktywne/webauth}"
    build: "${WEBAUTH_PATH:-./webauth}"
    depends_on:
      - authgate
      - certifier

  emigate:
    extends:
      file: ./emigate.yaml
      service: emigate
    image: "${EMIGATE_IMAGE:-radio-aktywne/emigate}"
    build: "${EMIGATE_PATH:-./emigate}"
    depends_on:
      - authgate
      - emishows
      - emistream
      - emipass
      - certifier

  authgate:
    extends:
      file: ./authgate.yaml
      service: authgate
    image: "${AUTHGATE_IMAGE:-radio-aktywne/authgate}"
    build: "${AUTHGATE_PATH:-./authgate}"
    depends_on:
      - authe
      - autho
      - certifier

  autho:
    extends:
      file: ./autho.yaml
      service: autho
    image: "${AUTHO_IMAGE:-radio-aktywne/autho}"
    build: "${AUTHO_PATH:-./autho}"
    depends_on:
      - authe
      - certifier

  authe:
    extends:
      file: ./authe.yaml
      service: authe
    image: "${AUTHE_IMAGE:-radio-aktywne/authe}"
    build: "${AUTHE_PATH:-./authe}"
    depends_on:
      - authe-db
      - certifier

  authe-db:
    extends:
      file: ./authe-db.yaml
      service: authe-db
    image: "${AUTHE_DB_IMAGE:-radio-aktywne/authe-db}"
    build: "${AUTHE_DB_PATH:-./authe-db}"
    depends_on:
      - certifier

  emipass:
    extends:
      file: ./emipass.yaml
      service: emipass
    image: "${EMIPASS_IMAGE:-radio-aktywne/emipass}"
    build: "${EMIPASS_PATH:-./emipass}"
    depends_on:
      - emistream

  webscheduler:
    extends:
      file: ./webscheduler.yaml
      service: webscheduler
    image: "${WEBSCHEDULER_IMAGE:-radio-aktywne/webscheduler}"
    build: "${WEBSCHEDULER_PATH:-./webscheduler}"
    depends_on:
      - emischeduler

  emischeduler:
    extends:
      file: ./emischeduler.yaml
      service: emischeduler
    image: "${EMISCHEDULER_IMAGE:-radio-aktywne/emischeduler}"
    build: "${EMISCHEDULER_PATH:-./emischeduler}"
    depends_on:
      - emishows
      - emistream
      - emiarchive

  emishows:
    extends:
      file: ./emishows.yaml
      service: emishows
    image: "${EMISHOWS_IMAGE:-radio-aktywne/emishows}"
    build: "${EMISHOWS_PATH:-./emishows}"
    depends_on:
      - emishows-db
      - emitimes

  emishows-db:
    extends:
      file: ./emishows-db.yaml
      service: emishows-db
    image: "${EMISHOWS_DB_IMAGE:-radio-aktywne/emishows-db}"
    build: "${EMISHOWS_DB_PATH:-./emishows-db}"

  emitimes:
    extends:
      file: ./emitimes.yaml
      service: emitimes
    image: "${EMITIMES_IMAGE:-radio-aktywne/emitimes}"
    build: "${EMITIMES_PATH:-./emitimes}"

  emistream:
    extends:
      file: ./emistream.yaml
      service: emistream
    image: "${EMISTREAM_IMAGE:-radio-aktywne/emistream}"
    build: "${EMISTREAM_PATH:-./emistream}"
    depends_on:
      - emirecorder
      - fusion

  emirecorder:
    extends:
      file: ./emirecorder.yaml
      service: emirecorder
    image: "${EMIRECORDER_IMAGE:-radio-aktywne/emirecorder}"
    build: "${EMIRECORDER_PATH:-./emirecorder}"
    depends_on:
      - emiarchive

  emiarchive:
    extends:
      file: ./emiarchive.yaml
      service: emiarchive
    image: "${EMIARCHIVE_IMAGE:-radio-aktywne/emiarchive}"
    build: "${EMIARCHIVE_PATH:-./emiarchive}"

  fusion:
    extends:
      file: ./fusion.yaml
      service: fusion
    image: "${FUSION_IMAGE:-radio-aktywne/fusion}"
    build: "${FUSION_PATH:-./fusion}"
    depends_on:
      - streamcast

  streamcast:
    extends:
      file: ./streamcast.yaml
      service: streamcast
    image: "${STREAMCAST_IMAGE:-radio-aktywne/streamcast}"
    build: "${STREAMCAST_PATH:-./streamcast}"

  proxy:
    extends:
      file: ./proxy.yaml
      service: proxy
    image: "${PROXY_IMAGE:-radio-aktywne/proxy}"
    build: "${PROXY_PATH:-./proxy}"
    depends_on:
      - certifier

  certifier:
    extends:
      file: ./certifier.yaml
      service: certifier
    image: "${CERTIFIER_IMAGE:-radio-aktywne/certifier}"
    build: "${CERTIFIER_PATH:-./certifier}"

volumes:
  authopsy-certs:
  webauth-certs:
  emigate-backend-certs:
  authgate-frontend-certs:
  authgate-backend-certs:
  autho-certs:
  authe-certs:
  authe-db:
  authe-db-certs:
  emischeduler:
  emishows-certs:
  emishows-db:
  emishows-db-certs:
  emitimes:
  emiarchive:
  proxy-frontend-certs:
  proxy-backend-certs:
