services:
  emiweb:
    extends:
      file: ./emiweb.yml
      service: emiweb
    image: "${EMIWEB_IMAGE:-radio-aktywne/emiweb}"
    build: "${EMIWEB_PATH:-./emiweb}"
    depends_on:
      - webauth
      - authgate
      - emigate

  webauth:
    extends:
      file: ./webauth.yml
      service: webauth
    image: "${WEBAUTH_IMAGE:-radio-aktywne/webauth}"
    build: "${WEBAUTH_PATH:-./webauth}"
    depends_on:
      - authgate

  emigate:
    extends:
      file: ./emigate.yml
      service: emigate
    image: "${EMIGATE_IMAGE:-radio-aktywne/emigate}"
    build: "${EMIGATE_PATH:-./emigate}"
    depends_on:
      - authgate
      - emishows
      - emistream
      - emipass

  authgate:
    extends:
      file: ./authgate.yml
      service: authgate
    image: "${AUTHGATE_IMAGE:-radio-aktywne/authgate}"
    build: "${AUTHGATE_PATH:-./authgate}"
    depends_on:
      - authe
      - autho

  autho:
    extends:
      file: ./autho.yml
      service: autho
    image: "${AUTHO_IMAGE:-radio-aktywne/autho}"
    build: "${AUTHO_PATH:-./autho}"
    depends_on:
      - authe

  authe:
    extends:
      file: ./authe.yml
      service: authe
    image: "${AUTHE_IMAGE:-radio-aktywne/authe}"
    build: "${AUTHE_PATH:-./authe}"
    depends_on:
      - authe-db

  authe-db:
    extends:
      file: ./authe-db.yml
      service: authe-db
    image: "${AUTHE_DB_IMAGE:-radio-aktywne/authe-db}"
    build: "${AUTHE_DB_PATH:-./authe-db}"

  emipass:
    extends:
      file: ./emipass.yml
      service: emipass
    image: "${EMIPASS_IMAGE:-radio-aktywne/emipass}"
    build: "${EMIPASS_PATH:-./emipass}"
    depends_on:
      - emistream

  emischeduler:
    extends:
      file: ./emischeduler.yml
      service: emischeduler
    image: "${EMISCHEDULER_IMAGE:-radio-aktywne/emischeduler}"
    build: "${EMISCHEDULER_PATH:-./emischeduler}"
    depends_on:
      - emischeduler-db
      - emishows
      - emistream
      - emiarchive

  emischeduler-db:
    extends:
      file: ./emischeduler-db.yml
      service: emischeduler-db
    image: "${EMISCHEDULER_DB_IMAGE:-radio-aktywne/emischeduler-db}"
    build: "${EMISCHEDULER_DB_PATH:-./emischeduler-db}"

  emishows:
    extends:
      file: ./emishows.yml
      service: emishows
    image: "${EMISHOWS_IMAGE:-radio-aktywne/emishows}"
    build: "${EMISHOWS_PATH:-./emishows}"
    depends_on:
      - emishows-db
      - emitimes

  emishows-db:
    extends:
      file: ./emishows-db.yml
      service: emishows-db
    image: "${EMISHOWS_DB_IMAGE:-radio-aktywne/emishows-db}"
    build: "${EMISHOWS_DB_PATH:-./emishows-db}"

  emitimes:
    extends:
      file: ./emitimes.yml
      service: emitimes
    image: "${EMITIMES_IMAGE:-radio-aktywne/emitimes}"
    build: "${EMITIMES_PATH:-./emitimes}"

  emistream:
    extends:
      file: ./emistream.yml
      service: emistream
    image: "${EMISTREAM_IMAGE:-radio-aktywne/emistream}"
    build: "${EMISTREAM_PATH:-./emistream}"
    depends_on:
      - emirecorder
      - fusion

  emirecorder:
    extends:
      file: ./emirecorder.yml
      service: emirecorder
    image: "${EMIRECORDER_IMAGE:-radio-aktywne/emirecorder}"
    build: "${EMIRECORDER_PATH:-./emirecorder}"
    depends_on:
      - emiarchive

  emiarchive:
    extends:
      file: ./emiarchive.yml
      service: emiarchive
    image: "${EMIARCHIVE_IMAGE:-radio-aktywne/emiarchive}"
    build: "${EMIARCHIVE_PATH:-./emiarchive}"

  fusion:
    extends:
      file: ./fusion.yml
      service: fusion
    image: "${FUSION_IMAGE:-radio-aktywne/fusion}"
    build: "${FUSION_PATH:-./fusion}"
    depends_on:
      - streamcast

  streamcast:
    extends:
      file: ./streamcast.yml
      service: streamcast
    image: "${STREAMCAST_IMAGE:-radio-aktywne/streamcast}"
    build: "${STREAMCAST_PATH:-./streamcast}"

volumes:
  authe-db:
  emischeduler-db:
  emishows-db:
  emitimes:
  emiarchive:
