services:
  emiweb:
    extends:
      file: ./emiweb.yml
      service: emiweb
    image: "${EMIWEB_IMAGE:-radio-aktywne/emiweb}"
    build: "${EMIWEB_PATH:-./emiweb}"
    depends_on:
      - emigate

  emigate:
    extends:
      file: ./emigate.yml
      service: emigate
    image: "${EMIGATE_IMAGE:-radio-aktywne/emigate}"
    build: "${EMIGATE_PATH:-./emigate}"
    depends_on:
#      - emistream
      - emipass

  emipass:
    extends:
      file: ./emipass.yml
      service: emipass
    image: "${EMIPASS_IMAGE:-radio-aktywne/emipass}"
    build: "${EMIPASS_PATH:-./emipass}"
    depends_on:
      - emistream

  emistream:
    extends:
      file: ./emistream.yml
      service: emistream
    image: "${EMISTREAM_IMAGE:-radio-aktywne/emistream}"
    build: "${EMISTREAM_PATH:-./emistream}"
    depends_on:
      - fusion

  fusion:
    extends:
      file: ./fusion.yml
      service: fusion
    image: "${FUSION_IMAGE:-radio-aktywne/fusion}"
    build: "${FUSION_PATH:-./fusion}"
    depends_on:
      - streamcast

  streamcast:
    extends:
      file: ./streamcast.yml
      service: streamcast
    image: "${STREAMCAST_IMAGE:-radio-aktywne/streamcast}"
    build: "${STREAMCAST_PATH:-./streamcast}"
