version: "3.9"

services:
  emiweb:
    extends:
      file: ./emiweb/docker-compose.yml
      service: emiweb
    depends_on:
      - emipass

  emipass:
    extends:
      file: ./emipass/docker-compose.yml
      service: emipass
    depends_on:
      - fusion

  fusion:
    extends:
      file: ./fusion/docker-compose.yml
      service: fusion
    depends_on:
      - decay

  decay:
    extends:
      file: ./decay/docker-compose.yml
      service: decay
