services:
  emiarchive:
    image: "${EMIARCHIVE_IMAGE:-ghcr.io/radio-aktywne/emiarchive}:${EMIARCHIVE_TAG:-latest}"
    ports:
      - "${EMIARCHIVE_PUBLISHED_PORT:-30000}:30000"
      - "${EMIARCHIVE_PUBLISHED_ADMIN_PORT:-30001}:30001"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emiarchive.rule=HostRegexp(`emiarchive{suffix:.*}.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.emiarchive.service=emiarchive"
      - "traefik.http.services.emiarchive.loadbalancer.server.port=30000"
      - "traefik.http.routers.emiarchive-admin.rule=HostRegexp(`emiarchive-admin{suffix:.*}.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.emiarchive-admin.service=emiarchive-admin"
      - "traefik.http.services.emiarchive-admin.loadbalancer.server.port=30001"
    environment:
      - "EMIARCHIVE_ADMIN_USER=${EMIARCHIVE_ADMIN_USER:-admin}"
      - "EMIARCHIVE_ADMIN_PASSWORD=${EMIARCHIVE_ADMIN_PASSWORD:-password}"
      - "EMIARCHIVE_READONLY_USER=${EMIARCHIVE_READONLY_USER:-readonly}"
      - "EMIARCHIVE_READONLY_PASSWORD=${EMIARCHIVE_READONLY_PASSWORD:-password}"
      - "EMIARCHIVE_READWRITE_USER=${EMIARCHIVE_READWRITE_USER:-readwrite}"
      - "EMIARCHIVE_READWRITE_PASSWORD=${EMIARCHIVE_READWRITE_PASSWORD:-password}"
    volumes:
      - emiarchive:/app/data
