services:
  emiarchive:
    image: "${EMIARCHIVE_IMAGE:-ghcr.io/radio-aktywne/emiarchive}:${EMIARCHIVE_TAG:-latest}"
    ports:
      - "${EMIARCHIVE_PUBLISHED_PORT:-30000}:30000"
      - "${EMIARCHIVE_PUBLISHED_ADMIN_PORT:-30001}:30001"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "EMIARCHIVE_ADMIN_PUBLIC_URL=${EMIARCHIVE_ADMIN_PUBLIC_URL:-https://emiarchive-admin.traefik.me}"
      - "EMIARCHIVE_ADMIN_USER=${EMIARCHIVE_ADMIN_USER:-admin}"
      - "EMIARCHIVE_ADMIN_PASSWORD=${EMIARCHIVE_ADMIN_PASSWORD:-password}"
      - "EMIARCHIVE_READONLY_USER=${EMIARCHIVE_READONLY_USER:-readonly}"
      - "EMIARCHIVE_READONLY_PASSWORD=${EMIARCHIVE_READONLY_PASSWORD:-password}"
      - "EMIARCHIVE_READWRITE_USER=${EMIARCHIVE_READWRITE_USER:-readwrite}"
      - "EMIARCHIVE_READWRITE_PASSWORD=${EMIARCHIVE_READWRITE_PASSWORD:-password}"
      - "EMIARCHIVE_LIVE_RECORDINGS_BUCKET=${EMIARCHIVE_LIVE_RECORDINGS_BUCKET:-live-recordings}"
      - "EMIARCHIVE_PRERECORDED_BUCKET=${EMIARCHIVE_PRERECORDED_BUCKET:-pre-recorded}"
    volumes:
      - emiarchive:/app/data
