services:
  emischeduler:
    image: "${EMISCHEDULER_IMAGE:-ghcr.io/radio-aktywne/emischeduler}:${EMISCHEDULER_TAG:-latest}"
    ports:
      - "${EMISCHEDULER_PUBLISHED_PORT:-33000}:33000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "EMISCHEDULER_EMISTREAM__HOST=${EMISCHEDULER_EMISTREAM__HOST:-emistream}"
      - "EMISCHEDULER_EMISTREAM__PORT=${EMISCHEDULER_EMISTREAM__PORT:-10000}"
      - "EMISCHEDULER_EMIARCHIVE__HOST=${EMISCHEDULER_EMIARCHIVE__HOST:-emiarchive}"
      - "EMISCHEDULER_EMIARCHIVE__PORT=${EMISCHEDULER_EMIARCHIVE__PORT:-30000}"
      - "EMISCHEDULER_EMIARCHIVE__USERNAME=${EMISCHEDULER_EMIARCHIVE__USERNAME:-readonly}"
      - "EMISCHEDULER_EMIARCHIVE__PASSWORD=${EMISCHEDULER_EMIARCHIVE__PASSWORD:-password}"
      - "EMISCHEDULER_EMISHOWS__HOST=${EMISCHEDULER_EMISHOWS__HOST:-emishows}"
      - "EMISCHEDULER_EMISHOWS__PORT=${EMISCHEDULER_EMISHOWS__PORT:-35000}"
      - "EMISCHEDULER_LOG_FILE=${EMISCHEDULER_LOG_FILE:-/etc/emischeduler/log.csv}"
      - "EMISCHEDULER_LIVE_RECORDINGS_BUCKET=${EMISCHEDULER_LIVE_RECORDINGS_BUCKET:-live-recordings}"
      - "EMISCHEDULER_PRE_RECORDED_BUCKET=${EMISCHEDULER_PRE_RECORDED_BUCKET:-pre-recorded}"
    volumes:
      - emischeduler:/etc/emischeduler
