services:
  emischeduler:
    image: "${EMISCHEDULER_IMAGE:-ghcr.io/radio-aktywne/emischeduler}:${EMISCHEDULER_TAG:-latest}"
    ports:
      - "${EMISCHEDULER_PUBLISHED_PORT:-33000}:33000"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emischeduler.rule=HostRegexp(`emischeduler{suffix:.*}.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.emischeduler.service=emischeduler"
      - "traefik.http.services.emischeduler.loadbalancer.server.port=33000"
    environment:
      - "EMISCHEDULER_DB_HOST=${EMISCHEDULER_DB_HOST:-emischeduler-db}"
      - "EMISCHEDULER_DB_PORT=${EMISCHEDULER_DB_PORT:-32000}"
      - "EMISCHEDULER_DB_PASSWORD=${EMISCHEDULER_DB_PASSWORD:-password}"
      - "EMISCHEDULER_ADMIN_USERNAME=${EMISCHEDULER_ADMIN_USERNAME:-admin}"
      - "EMISCHEDULER_ADMIN_PASSWORD=${EMISCHEDULER_ADMIN_PASSWORD:-password}"
      - "EMISCHEDULER_EMISTREAM_HOST=${EMISCHEDULER_EMISTREAM_HOST:-emistream}"
      - "EMISCHEDULER_EMISTREAM_PORT=${EMISCHEDULER_EMISTREAM_PORT:-10000}"
      - "EMISCHEDULER_EMIARCHIVE_HOST=${EMISCHEDULER_EMIARCHIVE_HOST:-emiarchive}"
      - "EMISCHEDULER_EMIARCHIVE_PORT=${EMISCHEDULER_EMIARCHIVE_PORT:-30000}"
      - "EMISCHEDULER_EMIARCHIVE_USERNAME=${EMISCHEDULER_EMIARCHIVE_USERNAME:-readonly}"
      - "EMISCHEDULER_EMIARCHIVE_PASSWORD=${EMISCHEDULER_EMIARCHIVE_PASSWORD:-password}"
      - "EMISCHEDULER_EMISHOWS_HOST=${EMISCHEDULER_EMISHOWS_HOST:-emishows}"
      - "EMISCHEDULER_EMISHOWS_PORT=${EMISCHEDULER_EMISHOWS_PORT:-35000}"
