services:
  emistream:
    image: "${EMISTREAM_IMAGE:-ghcr.io/radio-aktywne/emistream}:${EMISTREAM_TAG:-latest}"
    ports:
      - "${EMISTREAM_PUBLISHED_PORT:-10000}:10000"
      - "${EMISTREAM_PUBLISHED_PORT:-10000}:10000/udp"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "EMISTREAM_FUSION__HOST=${EMISTREAM_FUSION__HOST:-fusion}"
      - "EMISTREAM_FUSION__PORT=${EMISTREAM_FUSION__PORT:-9000}"
      - "EMISTREAM_EMIRECORDER__HOST=${EMISTREAM_EMIRECORDER__HOST:-emirecorder}"
      - "EMISTREAM_EMIRECORDER__PORT=${EMISTREAM_EMIRECORDER__PORT:-31000}"
      - "EMISTREAM_TIMEOUT=${EMISTREAM_TIMEOUT:-60}"
