services:
  emishows-db:
    image: "${EMISHOWS_DB_IMAGE:-ghcr.io/radio-aktywne/emishows-db}:${EMISHOWS_DB_TAG:-latest}"
    ports:
      - "${EMISHOWS_PUBLISHED_DB_PORT:-34000}:34000"
      - "${EMISHOWS_PUBLISHED_DB_ADMIN_PORT:-34001}:34001"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emishows-db-admin.rule=HostRegexp(`emishows-db-admin{suffix:.*}.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.emishows-db-admin.service=emishows-db-admin"
      - "traefik.http.services.emishows-db-admin.loadbalancer.server.port=34001"
      - "traefik.http.services.emishows-db-admin.loadbalancer.server.scheme=https"
      - "traefik.http.services.emishows-db-admin.loadbalancer.serverstransport=emishows-db-admin@file"
    environment:
      - "EMISHOWS_DB_PASSWORD=${EMISHOWS_DB_PASSWORD:-password}"
    volumes:
      - emishows-db:/app/cockroach-data
      - emishows-db-certs:/etc/certs/
