services:
  emishows:
    image: "${EMISHOWS_IMAGE:-ghcr.io/radio-aktywne/emishows}:${EMISHOWS_TAG:-latest}"
    ports:
      - "${EMISHOWS_PUBLISHED_PORT:-35000}:35000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "EMISHOWS_DB__HOST=${EMISHOWS_DB__HOST:-emishows-db}"
      - "EMISHOWS_DB__PORT=${EMISHOWS_DB__PORT:-34000}"
      - "EMISHOWS_DB__PASSWORD=${EMISHOWS_DB__PASSWORD:-password}"
      - "EMISHOWS_EMITIMES__HOST=${EMISHOWS_EMITIMES__HOST:-emitimes}"
      - "EMISHOWS_EMITIMES__PORT=${EMISHOWS_EMITIMES__PORT:-36000}"
      - "EMISHOWS_EMITIMES__USER=${EMISHOWS_EMITIMES__USER:-user}"
      - "EMISHOWS_EMITIMES__PASSWORD=${EMISHOWS_EMITIMES__PASSWORD:-password}"
      - "EMISHOWS_EMITIMES__CALENDAR=${EMISHOWS_EMITIMES__CALENDAR:-emitimes}"
    volumes:
      - emishows-certs:/etc/certs/
