services:
  emischeduler-db:
    image: "${EMISCHEDULER_DB_IMAGE:-ghcr.io/radio-aktywne/emischeduler-db}:${EMISCHEDULER_DB_TAG:-latest}"
    ports:
      - "${EMISCHEDULER_PUBLISHED_DB_PORT:-32000}:32000"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emischeduler-db.rule=HostRegexp(`emischeduler-db{suffix:.*}.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.emischeduler-db.service=emischeduler-db"
      - "traefik.http.services.emischeduler-db.loadbalancer.server.port=32000"
    environment:
      - "EMISCHEDULER_DB_PASSWORD=${EMISCHEDULER_DB_PASSWORD:-password}"
    volumes:
      - emischeduler-db:/app/redis-data
