services:
  emischeduler-db:
    image: "${EMISCHEDULER_DB_IMAGE:-ghcr.io/radio-aktywne/emischeduler-db}:${EMISCHEDULER_DB_TAG:-latest}"
    ports:
      - "${EMISCHEDULER_PUBLISHED_DB_PORT:-32000}:32000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "EMISCHEDULER_DB_PASSWORD=${EMISCHEDULER_DB_PASSWORD:-password}"
    volumes:
      - emischeduler-db:/app/redis-data
