services:
  emitimes:
    image: "${EMITIMES_IMAGE:-ghcr.io/radio-aktywne/emitimes}:${EMITIMES_TAG:-latest}"
    ports:
      - "${EMITIMES_PUBLISHED_PORT:-36000}:36000"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emitimes.rule=HostRegexp(`emitimes{suffix:.*}.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.emitimes.service=emitimes"
      - "traefik.http.services.emitimes.loadbalancer.server.port=36000"
    environment:
      - "EMITIMES_USER=${EMITIMES_USER:-user}"
      - "EMITIMES_PASSWORD=${EMITIMES_PASSWORD:-password}"
      - "EMITIMES_CALENDAR=${EMITIMES_CALENDAR:-emitimes}"
    volumes:
      - emitimes:/app/data
