services:
  emiweb:
    image: "${EMIWEB_IMAGE:-ghcr.io/radio-aktywne/emiweb}:${EMIWEB_TAG:-latest}"
    ports:
      - "${EMIWEB_FORWARDED_PORT:-11000}:11000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "EMIWEB_API_HOST=${EMIWEB_API_HOST:-host.docker.internal}"
      - "EMIWEB_API_PORT=${EMIWEB_API_PORT:-10000}"
