services:
  emiweb:
    image: "${EMIWEB_IMAGE:-ghcr.io/radio-aktywne/emiweb}:${EMIWEB_TAG:-latest}"
    ports:
      - "${EMIWEB_PUBLISHED_PORT:-13000}:13000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "EMIWEB_EMIGATE_URL=${EMIWEB_EMIGATE_URL:-http://emigate:12000}"
