services:
  fusion:
    image: "${FUSION_IMAGE:-ghcr.io/radio-aktywne/fusion}:${FUSION_TAG:-latest}"
    ports:
      - "${FUSION_PUBLISHED_LIVE_PORT:-9000}:9000/udp"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "FUSION_TARGET_ICECAST_HOST=${FUSION_TARGET_ICECAST_HOST:-streamcast}"
      - "FUSION_TARGET_ICECAST_PORT=${FUSION_TARGET_ICECAST_PORT:-8000}"
      - "FUSION_TARGET_ICECAST_PASSWORD=${FUSION_TARGET_ICECAST_PASSWORD:-hackme}"
      - "FUSION_TARGET_ICECAST_MOUNT=${FUSION_TARGET_ICECAST_MOUNT:-radio.mp3}"
