services:
  webauth:
    image: "${WEBAUTH_IMAGE:-ghcr.io/radio-aktywne/webauth}:${WEBAUTH_TAG:-latest}"
    ports:
      - "${WEBAUTH_PUBLISHED_PORT:-21000}:21000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - "WEBAUTH_AUTHGATE_URL=${WEBAUTH_AUTHGATE_URL:-https://authgate:20000}"
      - "WEBAUTH_COOKIE_DOMAIN=${WEBAUTH_COOKIE_DOMAIN:-traefik.me}"
    volumes:
      - webauth-certs:/etc/certs
