version: "3.9"

services:
  emipass:
    image: "${EMIPASS_IMAGE:-ghcr.io/radio-aktywne/emipass}:${EMIPASS_TAG:-latest}"
    ports:
      - "${EMIPASS_FORWARDED_SOURCE_PORT:-10000}:10000"
    environment:
      - "EMIPASS_TARGET_HOST=${EMIPASS_TARGET_HOST:-fusion}"
      - "EMIPASS_TARGET_PORT=${EMIPASS_TARGET_PORT:-9000}"
