api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"
    http:
      tls: { }

providers:
  file:
    directory: /etc/traefik/
    watch: true
  docker:
    exposedByDefault: false
