path: /etc/certs
default_identities:
  - "127.0.0.1"
  - "localhost"
  - "*.localhost"
  - "traefik.me"
  - "*.traefik.me"
certs:
  authopsy:
    type: self-signed
  webauth:
    type: self-signed
  emigate-backend:
    type: self-signed
  authgate-frontend:
    type: self-signed
    server:
      - identities:
          - authgate
  authgate-backend:
    type: self-signed
  autho:
    type: self-signed
    server:
      - { }
  authe:
    type: self-signed
    server:
      - { }
    client:
      - identities:
          - authe
  authe-db:
    type: self-signed
    ca_file: ca.crt
    server:
      - cert_file: node.crt
        key_file: node.key
        identities:
          - authe-db
          - node
      - cert_file: ui.crt
        key_file: ui.key
        identities:
          - authe-db
          - node
    client:
      - cert_file: client.root.crt
        key_file: client.root.key
        identities:
          - root
  emishows:
    type: self-signed
    client:
      - identities:
          - emishows
  emishows-db:
    type: self-signed
    ca_file: ca.crt
    server:
      - cert_file: node.crt
        key_file: node.key
        identities:
          - emishows-db
          - node
      - cert_file: ui.crt
        key_file: ui.key
        identities:
          - emishows-db
          - node
    client:
      - cert_file: client.root.crt
        key_file: client.root.key
        identities:
          - root
  proxy-frontend:
    type: traefik.me
  proxy-backend:
    type: self-signed
