version: "3.9"

services:
  decay:
    image: "${DECAY_IMAGE:-ghcr.io/radio-aktywne/decay}:${DECAY_TAG:-latest}"
    ports:
      - "${DECAY_FORWARDED_PORT:-8000}:8000"
    environment:
      - "DECAY_SOURCE_PASSWORD=${DECAY_SOURCE_PASSWORD:-hackme}"
      - "DECAY_RELAY_PASSWORD=${DECAY_RELAY_PASSWORD:-hackme}"
      - "DECAY_ADMIN_PASSWORD=${DECAY_ADMIN_PASSWORD:-admin}"
      - "DECAY_PASSWORD=${DECAY_PASSWORD:-hackme}"
      - "DECAY_HOST=${DECAY_HOST:-decay}"
